Repository Snooful/Snooful, pull requests merged in 2019-02, with the labels that each got.

#24 Add emoji-related commands
  package.json
  src/commands/emoji/emojiinfo.js
  src/commands/emoji/emojis.js
  src/commands/emoji/hasemoji.js
  src/locales.json
  src/utils/has-emoji.js
Labels: enhancement

#26 Add the event message setter utility
  src/commands/eventmessage/setjoinmessage.js
  src/commands/eventmessage/setleavemessage.js
  src/commands/setjoinmessage.js
  src/commands/setleavemessage.js
  src/locales.json
  src/utils/event-message-setter.js
Labels: enhancement

#31 Add tests for localization completeness
  src/locales.json
  test.js
Labels: tests

#28 Add permissions
  package.json
  src/commands/permissions/createrole.js
  src/commands/permissions/deleterole.js
  src/commands/permissions/giveperm.js
  src/commands/permissions/giverole.js
  src/commands/permissions/roles.js
  src/commands/permissions/takeperm.js
  src/commands/permissions/takerole.js
  src/commands/permissions/updatemods.js
  src/commands/permissions/userperms.js
  src/index.js
  src/locales.json
  src/utils/role-name.js
  src/utils/user-perms.js
Labels: enhancement

#32 Add tests for commands
  package.json
  src/commands/eventmessage/setjoinmessage.js
  src/commands/eventmessage/setleavemessage.js
  src/commands/fun/birthday.js
  src/commands/fun/echo.js
  src/commands/fun/feed.js
  src/commands/fun/lmgtfy.js
  src/commands/fun/mock.js
  src/commands/fun/urban.js
  src/commands/permissions/createrole.js
  src/commands/permissions/deleterole.js
  src/commands/permissions/giveperm.js
  src/commands/permissions/giverole.js
  src/commands/permissions/roles.js
  src/commands/permissions/takeperm.js
  src/commands/permissions/takerole.js
  src/commands/permissions/updatemods.js
  src/commands/permissions/userperms.js
  src/commands/util/bytes.js
  src/commands/util/duration.js
  src/commands/util/reverse.js
  src/commands/util/time.js
  src/commands/util/whereami.js
  src/commands/util/whoami.js
  tests/commands.js
  tests/localization.js
Labels: tests

#33 Truncate Urban Dictionary definitions to 120 characters
  package.json
  src/commands/fun/urban.js
Labels: enhancement

#34 Update all Spanish localizations
  src/locales.json
Labels: localization
